# Generated by Django 4.1.5 on 2023-01-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_address_town_address_city_address_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
